### ISSUE TITLE
It should support index

### ISSUE THREAD

**Issue by tom-tan** [tom-tan/cwl-inspector#2]
The following command fails but it should work!
`cwl-inspector` should recognize `position` field for inputs/outputs.

Input: echo.cwl
```yaml
class: CommandLineTool
cwlVersion: v1.0
id: echo_cwl
baseCommand:
  - cowsay
inputs:
  - id: input
    type: string?
    inputBinding:
      position: 0
    label: Input string
    doc: This is an input string
outputs:
  - id: output
    type: string?
    outputBinding: {}
requirements:
  - class: DockerRequirement
    dockerPull: docker/whalesay
```

Expected:
```console
$ cwl-inspector.rb echo.cwl inputs.0.label
Input string
```

Actual:
```console
$ cwl-inspector.rb echo.cwl inputs.0.label
./cwl-inspector.rb:28:in `block in inspect_pos': No such field inputs.0.label (RuntimeError)
        from ./cwl-inspector.rb:7:in `each'
        from ./cwl-inspector.rb:7:in `reduce'
        from ./cwl-inspector.rb:7:in `inspect_pos'
        from ./cwl-inspector.rb:97:in `cwl_inspect'
        from ./cwl-inspector.rb:116:in `<main>'
```
